import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";
const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e2e2e2",
        "on-secondary-container": "#765f3d",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1c1b1b",
        "secondary-container": "#fbdbb0",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        background: "#f9f9f9",
        "on-surface-variant": "#444748",
        primary: "#000000",
        "on-background": "#1a1c1c",
        "surface-dim": "#dadada",
        "inverse-surface": "#2f3131",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#838484",
        "primary-fixed": "#e5e2e1",
        "on-error": "#ffffff",
        surface: "#f9f9f9",
        "secondary-fixed": "#feddb3",
        "surface-container": "#eeeeee",
        "secondary-fixed-dim": "#e1c299",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-variant": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "tertiary-container": "#1a1c1c",
        "on-secondary-fixed": "#281801",
        secondary: "#725a39",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-container": "#858383",
        error: "#ba1a1a",
        outline: "#747878",
        "inverse-primary": "#c8c6c5",
        "surface-tint": "#5f5e5e",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f0f1f1",
        tertiary: "#000000",
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#584324",
        "outline-variant": "#c4c7c7",
        "on-error-container": "#93000a",
        "primary-container": "#1c1b1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-tablet": "40px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Playfair Display"],
        "display-xl-mobile": ["Playfair Display"],
        "label-caps": ["Inter"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Inter"],
        "headline-md": ["Playfair Display"],
        "display-xl": ["Playfair Display"],
        button: ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "400" }],
        "display-xl-mobile": [
          "48px",
          { lineHeight: "54px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "display-xl": [
          "80px",
          { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        button: [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
    },
  },
    plugins: [forms, containerQueries],
};
export default config;
